version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./tmp/db:/var/lib/mysql
  rails: &app_base
    build:
      context: .
    command:  /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_PORT: 3306
      TZ: "Asia/Tokyo"
      BUNDLE_JOBS: 4
      BUNDLE_PATH: /app/vendor/bundle
    volumes:
      - ".:/app"
      - bundle:/app/vendor/bundle
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  webpacker:
    <<: *app_base
    command: "bin/webpack-dev-server"
    ports:
      - "3035:3035"
    depends_on:
      - rails
    tty: false
    stdin_open: false
volumes:
  db:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local